WIP
crate/crate-docs pull request #85
Opened 2021-05-26 12:08 UTC by norosa

WIP

summary context for now:

- was partway through migrating old wiki content to new `dev/docs` dir. realized I could really do with automated link checks for the document I was writing. don't want to re-invent the wheel. may as well move into sphinx and take advantage of our existing infra

- while I'm at it, why not move existing RST files under `style` into sphinx for the same reason (haven't done this yet. also haven't moved the wiki exports I already added to `devs/docs`)

- named the project "doing the docs at crate.io" for now. will be sparse at first. but a good replacement for our old private wiki and something we can grow over time

- expect I can find some extra bits and bobs to sprinkle in before merging

2021-05-26 12:09 UTC, norosa commented
checkpoint commit because I want to add a new module to the crate-docs-theme and I would like to reference my WIP to justify my change. PR incoming shortly

2021-05-26 12:39 UTC, amotl requested changes
Hi Naomi,

thank you for all of those refinements. While I recognize this patch is still in draft mode, I quickly took a look and added some comments as suggestions. I believe most of them are merely typos.

With kind regards,
Andreas.

2021-05-26 12:39 UTC, amotl commented on docs/index.rst
> +    We have designed this project so that it also function as a reference
```suggestion
    We have designed this project so that it also functions as a reference
```

2021-05-26 12:39 UTC, amotl commented on docs/linking.rst
> +readability and use of character space..
```suggestion
readability and use of character space.
```

2021-05-26 12:39 UTC, amotl commented on docs/linking.rst
> +for ecample, in the case of the CrateDB Reference,
```suggestion
for example, in the case of the CrateDB reference documentation,
```

2021-05-26 12:39 UTC, amotl commented on docs/linking.rst
> +IF you copy the URL from your browser when you want to link to a page in the
```suggestion
If you copy the URL from your browser when you want to link to a page in the
```

2021-05-26 12:39 UTC, amotl commented on docs/linking.rst
> +version. This is fine for in most cases (e.g., for most day-to-day use by
```suggestion
version. This is fine in most cases (e.g., for most day-to-day use by
```

2021-05-26 12:39 UTC, amotl commented on docs/linking.rst
> +cases, you should link using a URL that uses the `latest` version. Doing so
```suggestion
cases, you should link using a URL that uses the ``latest`` version. Doing so
```

2021-05-26 12:39 UTC, amotl commented on docs/linking.rst
> +Let's say you are adding content to the `inserts performance` section of the CrateDB How-To Guides.
```suggestion
Let's say you are adding content to the `inserts performance`_ section of the CrateDB How-To Guides.
```

2021-05-26 12:39 UTC, amotl commented on docs/projects/post-release.rst
> +When `CrateDB`_ makes a new stable release, the CrateDB release manager will
```suggestion
When CrateDB_ makes a new stable release, the CrateDB release manager will
```

2021-05-26 12:39 UTC, amotl commented on docs/projects/post-release.rst
> +The `CrateDB docs` make use of a special ``latest`` version in the `Read The
```suggestion
The `CrateDB docs`_ make use of a special ``latest`` version in the `Read The
```

2021-05-26 12:39 UTC, amotl commented on docs/projects/post-release.rst
> +- Each active release line should have a corresponding entry this section, like so:
Not sure about this?

```suggestion
- Each active release line should have a corresponding entry, like so:
```

2021-05-26 12:39 UTC, amotl commented on docs/projects/post-release.rst
> +  This redirect checks for any 4.x version that doesn't match the latest feature release (e.g., ``4.1`) for that release line and redirects the request to the latest feature release version (e.g., ``
```suggestion
  This redirect checks for any 4.x version that doesn't match the latest feature release (e.g., ``4.1``) for that release line and redirects the request to the latest feature release version (e.g., ``4.1``). In this example, this redirect forces all 4.x versions to resolve to 4.1.
```

2021-05-26 15:33 UTC, norosa commented on docs/projects/post-release.rst
> +  This redirect checks for any 4.x version that doesn't match the latest feature release (e.g., ``4.1`) for that release line and redirects the request to the latest feature release version (e.g., ``
nice catch

2021-05-26 15:34 UTC, norosa commented
@amotl hehe thanks for the (very) early review. pushed some fixups. only one I didn't apply. left a comment. more to come soon

2021-05-27 11:53 UTC, amotl commented on docs/projects/post-release.rst
> +When `CrateDB`_ makes a new stable release, the CrateDB release manager will
All right, it's fine!

2021-07-28 18:05 UTC, amotl requested changes
Hi Naomi,

there might be a chance to get this patch merged? However, I requested a specific change about removing information which I believe is too specific for this general/public repository.

With kind regards,
Andreas.

2021-07-28 18:05 UTC, amotl commented on docs/projects/post-release.rst
> +================================
Hi Naomi,

when thinking about this again, I believe we should not publish that kind of specific information here. Can you remove this document `post-release.rst` completely?

With kind regards,
Andreas.

2021-12-02 17:44 UTC, closed without merging